spring:
  datasource:
    druid:
      url: jdbc:postgresql://localhost:5432/newswebsite
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      stat-view-servlet:
        login-username: admin
        login-password: admin
