server:
  port: 8763
spring:
  application:
    name: user
  rabbitmq:
        host: 127.0.0.1
        port: 15672
        username: guest
        password: guest
        virtualHost: /
        publisherConfirms: true
management:
    endpoints:
        web:
            exposure:
                include: refresh,health,info
